version: "3.9"

networks:
    essence:

services:
  web:
      container_name: web
      build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile.nginx
      volumes:
        - ./src:/var/www/html
        # - ./docker/nginx/nginx.conf:/tmp/nginx.conf
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
        - 443:443
      depends_on:
        - php-fpm
      networks:
        - essence
  php-fpm:
      container_name: php-fpm
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
      restart: always
      volumes:
        - ./src:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      environment:
        APP_ENV: local
      networks:
        - essence
  # redis:
  #     image: redis
  #     restart: always
  #     volumes: 
  #       - ./data/redis:/data
  #     networks:
  #       - essence
  db:
      container_name: db
      image: mariadb
      restart: always
      environment:
          MARIADB_DATABASE: essence
          MARIADB_USER: anhld4
          MARIADB_PASSWORD: 123
          MARIADB_ROOT_PASSWORD: 123
      ports:
          - 3310:3306
      volumes:
          - ./data/mysql:/var/lib/mysql
      networks:
          - essence
  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          - PMA_ARBITRARY=1
          - UPLOAD_LIMIT=500M
      networks:
          - essence
